# Generated by Django 4.2.10 on 2024-03-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locationOne',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locationThree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locationTwo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
