# Generated by Django 4.2.10 on 2024-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('locationOne', models.CharField(max_length=50)),
                ('locationTwo', models.CharField(max_length=50)),
                ('locationThree', models.CharField(max_length=50)),
            ],
        ),
    ]
